name: Create Release Branch

on:
  push:
    branches:
      - master

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Create Release Branch
        run: |
          git checkout -b release
          mkdir dist_temp
          rsync -av lib/dist/ dist_temp/
          git rm -rf .
          rsync -av dist_temp/ .
          rm -rf dist_temp
          git add .
          git commit -m "Update release branch"

      - name: Push Release Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
