name: Create GitHub Pages Branch

on:
  push:
    branches:
      - master

jobs:
  create_github_pages_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "cuentafrst@gmail.com"
          git config --global user.name "Armando"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build app project
        run: |
          yarn build:app
          find . -name "node_modules" -type d -prune -exec rm -rf {} +

      - name: Create GitHub Pages Branch
        run: |
          git checkout -b gh-pages
          mkdir dist_temp
          rsync -av docs/* dist_temp/
          git rm -rf .
          rsync -av dist_temp/ .
          rm -rf dist_temp
          git add .
          git commit -m "Build static site."

      - name: Push GitHub Pages Branch
        run: git push --force origin gh-pages

      - name: Push GitHub Pages Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
